version: '3'
services:
  competence_mongo_db:
    image: mongo:latest
    container_name: competence_susi_db
    hostname: competence_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=comp
      - MONGO_INITDB_ROOT_PASSWORD=comp
    ports:
      - 28777:27017
    networks:
      competence_network:
          ipv4_address: 10.20.0.10

  competence_mapper:
    image: competence:latest
    container_name: competence_mapper
    hostname: competence_mapper
    ports:
      - 3000:3000
      - 8080:8080
    networks:
      competence_network:
          ipv4_address: 10.20.0.20

networks:
  competence_network:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "10.20.0.0/24"
                gateway: "10.20.0.1"